[package]
name = "tera_design"
version = "0.1.1"
authors = ["Andras Mocsary <nobody@reedwolf.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
tera = "0.11.20"
actix-web = "1.0.0-rc"
log = "0.4.6"
serde = "1.0"
serde_json = "1.0.39"
actix-files = "0.1.0"
